name: Deploy Javadoc

on:
  push:
    branches: [ master ]

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Generate Javadoc
        run: mvn clean compile javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/docs/javadoc
          token: ${{ secrets.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 }}